#腾讯云短信
tencent:
  msm:
    secret_id: AKIDCDxRfcIhpgGZbNt86oFQKyKPDk0zg6G9
    secret_key: e18yXprc6JFuIPFp8AvRgeLktlMgkX3I
    #短信应用 ID
    app_id: 1400613395
    #短信签名内容
    sign_name: VernHe
    #短信模板ID
    template_id: 1248012