server:
  port: 9002
  servlet:
    context-path:
  compression:
    enabled: true
    mime-types: application/json
  tomcat: # see from ServerProperties
    basedir: ./
    accesslog:
      enabled: true
      directory: ./
      pattern: '%h %l %u %t %s %T "%r" %b "%{User-Agent}i"'
#腾讯云的配置信息
tencent-cloud:
  secretId: {{ .secretId }}
  secretKey: {{ .secretKey }}
  #短信SdkAppId在 [短信控制台] 添加应用后生成的实际SdkAppId
  sdkAppId: {{ .sdkAppId }}
  #短信签名，短信【】中的内容
  signName: {{ .signName }}
  #短信模板ID
  templateId: {{ templateId }}
  #验证码的有效期,单位是分钟
  expires: 3

mongo-redis:
  host: {{ .host }}

spring:
  data:
    mongodb:
      host: ${mongo-redis.host}
      port: 27017
      database: {{ .database }}
      password: {{ .password }}
      username: admin
#      uri: mongodb://admin:123456@${mongo-redis.host}:20085/chat-admin
      authentication-database: admin
      option:
        max-connection-idle-time: 900000
        max-connection-per-host: 200
        min-connection-per-host: 20
        socket-timeout: 30000
        threads-allowed-to-block-for-connection-multiplier: 10
  redis:
    database: 10
    host: ${mongo-redis.host}
    password: {{ .password }}
    port: {{ .port }}
    timeout: 10000
    lettuce:
      pool:
        max-active: 300
        max-idle: 8
        max-wait: 2000
        min-idle: 0
      shutdown-timeout: 100
        # ====================================================================================
        # spring-redis-redisson
        # ====================================================================================
    redisson:
      # file: classpath:redisson.yaml
      config:
        #单机
        singleServerConfig:
          password: {{ .password }}
          timeout: 10000
          address: redis://${mongo-redis.host}:20081
#
#        # 集群
#        clusterServersConfig:
#            nodeAddresses:
#            - "redis://10.210.13.203:6381"
#            - "redis://10.210.13.203:6382"
#            - "redis://10.210.13.203:6383"
#            - "redis://10.210.13.203:6384"
#            - "redis://10.210.13.203:6385"
#            - "redis://10.210.13.203:6386"
#            password: null
#            loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#            slaveConnectionMinimumIdleSize: 8
#            slaveConnectionPoolSize: 16
#            sslEnableEndpointIdentification: false
#            timeout: 3000
#
#        # 所有Redis节点客户端之间共享的线程数量，默认值: 当前处理核数量 * 2
#        threads: 24
#        # Netty线程池数量，默认值: 当前处理核数量 * 2
#        nettyThreads: 12
#        # 传输模式，默认值：NIO
#        transportMode: NIO
  ##发送qq邮件配置
  mail:
    ##邮箱服务器地址
    host: smtp.qq.com
    # 非ssl 25  ssl 587
    port: 587
    username: {{ .username }} #发送方邮箱
    password: {{ .password }} #smtp口令
    mailFromNick: {{ .mailFromNick }} #发件人昵称
    default-encoding: UTF-8
    #使用ssl通道发送qq邮件
    properties:
      mail:
        smtp:
          socketFactory:
            class=javax:
              net:
                ssl:
                  SSLSocketFactory:
          auth: true
          starttls:
            enable: true
            required: true
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 604800 # 7天
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
#线程池的配置
task:
  pool:
    keepAliveSeconds: 300 #设置线程活跃时间（秒）
    queueCapacity: 200 #设置队列容量
    threadNamePrefix: thread-pool-service-
#七牛云存储